name: Main

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'
    - run: yarn install
    - run: yarn run audit-ci
    - run: yarn run build
    - run: yarn run test
